name: tp0
services:
    server:
        container_name: server
        image: server:latest
        entrypoint: python3 /main.py
        environment:
            - PYTHONUNBUFFERED=1
            - AGENCIES_COUNT=3
        networks:
          testing_net:
            ipv4_address: 172.25.125.2
        volumes:
            - ./server/config.ini:/config.ini
    client1:
        container_name: client1
        image: client:latest
        entrypoint: /client
        environment:
            - CLI_ID=1
            - CLI_SERVER_IP=172.25.125.2:12345
            - NAME=name1
            - SURNAME=surname1
            - DNI=1001
            - BIRTHDAY=1990-01-01
            - NUMBER=101
        networks:
            - testing_net 
        depends_on:
            - server
        volumes:
            - ./client/config.yaml:/config.yaml
            - ./.data/agency-1.csv:/data/agency-1.csv
    client2:
        container_name: client2
        image: client:latest
        entrypoint: /client
        environment:
            - CLI_ID=2
            - CLI_SERVER_IP=172.25.125.2:12345
            - NAME=name2
            - SURNAME=surname2
            - DNI=1002
            - BIRTHDAY=1990-01-01
            - NUMBER=102
        networks:
            - testing_net 
        depends_on:
            - server
        volumes:
            - ./client/config.yaml:/config.yaml
            - ./.data/agency-2.csv:/data/agency-2.csv
    client3:
        container_name: client3
        image: client:latest
        entrypoint: /client
        environment:
            - CLI_ID=3
            - CLI_SERVER_IP=172.25.125.2:12345
            - NAME=name3
            - SURNAME=surname3
            - DNI=1003
            - BIRTHDAY=1990-01-01
            - NUMBER=103
        networks:
            - testing_net 
        depends_on:
            - server
        volumes:
            - ./client/config.yaml:/config.yaml
            - ./.data/agency-3.csv:/data/agency-3.csv
networks:
    testing_net:
        ipam:
            driver: default
            config:
               - subnet: 172.25.125.0/24
